### ISSUE TITLE
Phraseexpress is outdated, can you please update.

### ISSUE THREAD

**Issue by marius-hh** [bc3tech/chocolatey#24]
chocolatey/PhraseExpress/PhraseExpress/phraseexpress.nuspec

**Comment by bc3tech** [comment]
In fact it is not; only the version shown on Chocolatey is "outdated" but the _content_ of what gets downloaded is always the latest due to the way PhraseExpress posts new downloads (same filename/url every time for new version).

Nevertheless, I queued [a new build w/ the new version #](https://github.com/bc3tech/chocolatey/actions/runs/1693744006)

**Comment by marius-hh** [comment]
> In fact it is not; only the version shown on Chocolatey is "outdated" but the _content_ of what gets downloaded is always the latest due to the way PhraseExpress posts new downloads (same filename/url every time for new version).
> 
> Nevertheless, I queued [a new build w/ the new version #](https://github.com/bc3tech/chocolatey/actions/runs/1693744006)

Thanks.
If the version number in chocolatey is not correct, it will not be updated automatically.
Is there any way I can trigger it myself?

**Comment by bc3tech** [comment]
either 
`cup phraseexpress.portable --force`
or
`cup phraseexpress.install --force`
depending on which you've installed.

**Comment by marius-hh** [comment]
Thanks. I didn't mean how to install the new version on my client. I meant to create a new package with the right version at chocolatey as maintainer, that it will be updated automaticly with the command `cup all`.

**Comment by bc3tech** [comment]
ah, unfortunately no only maintainers of this repo can do that today. So for now reporting here or on PhraseExpress' entry on chocolatey.org is the best/only way.
